### ISSUE TITLE
aikido rviz always fails

### ISSUE THREAD

**Issue by vinitha910** [personalrobotics/aikido#128]
aikido rviz always fails silently because of dependencies (libmicrohttpd)

**Comment by psigen** [comment]
Perhaps now would be a good time to think a bit if a header-only implementation would be useful here, since the requirements are relatively simple (serving static content).

https://github.com/yhirose/cpp-httplib

**Comment by jslee02** [comment]
I believe we could close this issue because the dependency of `libmicrohttpd` is explicitly added in #149, and `rviz` component is being built in CI testing.

@psigen Do you mean making Aikido header-only project? If so, I think we should create an issue for that separately.

**Comment by psigen** [comment]
No, I mean that we could use a header-only implementation of an HTTP server so that we do not have to depend on libmicrohttpd, which is not exactly common and adds another non-standard rosdep key.

**Comment by jslee02** [comment]
Oh, I see. I don't have an objection to using a header-only library as long as it meets our requirements and is mature enough.

**Comment by jslee02** [comment]
I created an issue for using a header-only library to continue the discussion there. Closing this issue.
