### ISSUE TITLE
Shape Conversion always fails

### ISSUE THREAD

**Issue by vinitha910** [personalrobotics/aikido#129]
https://github.com/personalrobotics/aikido/blob/master/src/rviz/shape_conversions.cpp#L93

This line should be changed to `true` otherwise shape conversion always fails

**Comment by ClintLiddick** [comment]
@vinitha910 you've assigned this to yourself. If/when you make a PR reference this issue so I can track it. Thanks!

**Comment by jslee02** [comment]
I believe this is resolved by #130.
