### ISSUE TITLE
Disable Reviewable integration

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/aikido#145]
[Github now has a built-in code review system](https://github.com/features) that integrates nicely with the UI and branch protection. While this system isn't perfect, it does seem to be quite a bit more polished than Reviewable. I would like to disable Reviewable on Aikido and switch to using Github code review.

@psigen @jslee02 Any objections?

**Comment by psigen** [comment]
I am in support of this, I have not been using Reviewable lately because it
is very slow to load for me.

**Comment by jslee02** [comment]
Yeah, we've used it because there was no alternative that allows us to review the whole diff when it's large. The GitHub's built-in review system looks good enough for our use to me.

**Comment by brianhou** [comment]
Closing -- I flipped the switch on the Reviewable page.
