### ISSUE TITLE
Support ClangFormat 3.9 and later

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#162]
Currently, Aikido only supports 3.8 because different versions result in different code formatting with the same configuration. However, this constraint might be an unnecessary inconvenience if there is a way to workaround this.

[This](https://github.com/personalrobotics/aikido/pull/153#discussion_r110524211) is a related comment.

**Comment by brianhou** [comment]
We upgraded to 6.0 in #547. As @jslee02 noted originally, there are some minor formatting differences so unfortunately we still need to standardize on a specific version.
