### ISSUE TITLE
Create custom FindRviz.cmake

### ISSUE THREAD

**Issue by psigen** [personalrobotics/aikido#197]
Due to the issue here:
https://github.com/personalrobotics/aikido/blob/master/src/rviz/CMakeLists.txt#L10

it seems like maybe we should create a `FindRviz.cmake` that contains this logic and put it in `./cmake` so that we can simply call `find_package(rviz)` as needed.

**Comment by jslee02** [comment]
:+1: to the idea.

I wonder which one should be used for the library name between `interactive_markers` and `rvis`, though. :confused:

**Comment by psigen** [comment]
Oh, probably should use `interactive_markers`, to override the existing non-working one?

**Comment by jslee02** [comment]
Created PR #198 for this.
