### ISSUE TITLE
Set up automated style-checking for c++ code.

### ISSUE THREAD

**Issue by psigen** [personalrobotics/aikido#21]
It can be really hard to validate style conventions when reviewing PRs.  Let's try to set up automated style checking for `aikido` before the codebase gets too large.

Some promising options:
- https://github.com/alexmurray/cstyle
- http://astyle.sourceforge.net/
- https://bitbucket.org/verateam/vera/wiki/Home
- https://github.com/kunaltyagi/nsiqcppstyle

**Comment by jslee02** [comment]
Resolved by #116
