### ISSUE TITLE
Resolve sampling interface for point TSRs 

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/aikido#22]
The current `aikido::constraint::SampleGenerator` interface implies a strong distinction between a finite and infinite sequence of samples (via the `getNumSamples()` and `canSample()` methods).  This distinction might be useful e.g. for planners which want to populate their graphs with unique start and goal vertices.  The `aikido::constraint::TSR` class currently handles point TSRs (defined with no freedoms at the `w` frame) as an infinite sequence of identical samples, which may be a problem for planners which naively implement against the `SampleGenerator` API.  We should decide how we'd like to handle such cases in a way that is clear to both (a) planners that may make use of `SampleGenerator`s and (b) users who are constructing `TSR`s.  This is important because I expect that all existing users of TSRs commonly use point TSRs to specify pose constraints, so if our software handles this differently (e.g. via a dedicated `PoseConstraint` class, which I'm in favor of in any case), we should at least document it well (e.g. by throwing a warning when a point TSR is constructed).

**Comment by egordon** [comment]
Addressed by #13
