### ISSUE TITLE
Fix IkSampleableConstraint to handle finite pose constraints

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/aikido#23]
The current aikido::constraint::SampleGenerator interface implies a strong distinction between a finite and infinite sequence of samples (via the getNumSamples() and canSample() methods).  The current implementation of `aikido::constraint::IkSampleableConstraint` uses a generator for its underlying pose constraint.  If this pose generator samples from a finite set of samples, then the `IkSampleableConstraint` generator will also return a finite set, even if there exists an infinite sequence of actual samples (e.g. because of kinematic redundancy).  Even in the case that the IK set is finite (e.g. due to a 6-DOF arm), there are often multiple solutions for each pose sample.

**Comment by egordon** [comment]
Fixed by #13 and #22
