### ISSUE TITLE
Make code formatting script as a CMake module

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#232]
Currently, the code formatting CMake code is included in the main `CMakeLists.txt`. Since we may want to have this functionality for other projects, it would be good to make it as a CMake module file (like [Components.cmake](https://github.com/personalrobotics/aikido/blob/master/cmake/Components.cmake)) and disseminate it to other projects.

**Comment by jslee02** [comment]
[Here](https://github.com/personalrobotics/chimera/blob/master/cmake/ClangFormat.cmake) is an example I did for Chimera. One possible improvement is allowing to configure ClangFormat version instead of using hard-coded version.

**Comment by brianhou** [comment]
Resolved by #509.
