### ISSUE TITLE
Incorrect box constraint initialization in `computeJointVelocityFromTwist`

### ISSUE THREAD

**Issue by dqyi11** [personalrobotics/aikido#257]

**Comment by dqyi11** [comment]
In current implementation, initial guess is unset (by default all elements are zero).
When upper bounds and lower bounds are same signs, initial guess will be out of bounds, thus `NLopt` will throw an invalid argument error.

We will use current velocities of MetaSkeleton as initial guess.
Initial guess will be updated according to upper and lower bounds.

**Comment by mkoval** [comment]
Good catch! That explains why we were seeing that warning, even though having upper and lower bounds with the same sign is not an issue. Your fix makes sense to me.

**Comment by dqyi11** [comment]
Fixed in #262
