### ISSUE TITLE
Travis CI is silent even when it fails to build AIKIDO

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#269]
See [this](https://travis-ci.org/personalrobotics/aikido/jobs/308102385#L1846-L1856) and [this](https://travis-ci.org/personalrobotics/aikido/jobs/308102321#L3293).

**Comment by brianhou** [comment]
I think the silent failing issue may be because that we're missing `set -ev` in all of our `.ci` scripts?

**Comment by jslee02** [comment]
What `set -ev` does do?

**Comment by brianhou** [comment]
`-e` causes the script to exit immediately after a command fails, which I think will set the error code correctly for Travis. `-v` is just to be verbose and include the commands that are being run, which might be helpful for debugging.

I think we should merge https://github.com/personalrobotics/pr-cleanroom/pull/7 first. If that doesn't cause Travis to fail, we should then see if we need to add `-e` to the `.ci` scripts in #270.

**Comment by jslee02** [comment]
Thanks for the explanation!

Let's close this issue once it's confirmed if personalrobotics/pr-cleanroom#7 actually fixes this issue. Reopening for now.

**Comment by brianhou** [comment]
Resolved by #279.
