### ISSUE TITLE
aikido_rviz doesn't seem to properly install headers

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/aikido#30]
When I do a `sudo make install` on `aikido_rviz` I get the following output

```
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/_setup_util.py
-- Up-to-date: /usr/local/env.sh
-- Up-to-date: /usr/local/setup.bash
-- Up-to-date: /usr/local/setup.sh
-- Up-to-date: /usr/local/setup.zsh
-- Up-to-date: /usr/local/.rosinstall
-- Up-to-date: /usr/local/lib/pkgconfig/aikido_rviz.pc
-- Up-to-date: /usr/local/share/aikido_rviz/cmake/aikido_rvizConfig.cmake
-- Up-to-date: /usr/local/share/aikido_rviz/cmake/aikido_rvizConfig-version.cmake
-- Up-to-date: /usr/local/share/aikido_rviz/package.xml
-- Up-to-date: /usr/local/lib/libaikido_rviz.so
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/aikido_rviz.so
```

It seems to be installing the `.so` files, but doesn't install any header files. Consequently `aikido_rviz_INCLUDE_DIRS` appears to be empty in `aikido_rvizConfig.cmake`?

**Comment by jslee02** [comment]
`aikido_rviz` was merged into `aikido`, and it seems [all the necessary headers are installed](https://github.com/personalrobotics/aikido/pull/107/files#diff-af3b638bc2a3e6c650974192a53c7291R223) (copy the whole include directory). Closing this. Please reopen if it's not actually resolved.
