### ISSUE TITLE
Warnings from Doxygen

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#329]
There are a bunch of [warnings](https://gist.github.com/jslee02/24d457c99c8d44452c19b78e9417b1e0) from Doxygen when we run `make docs`. Mostly, its' because the argument names aren't consistent with the docstring.

**Comment by brianhou** [comment]
With the verbose Doxygen output removed: [aikido_doxygen_warnings.txt](https://github.com/personalrobotics/aikido/files/1757002/aikido_doxygen_warnings.txt)

**Comment by sniyaz** [comment]
Thanks! Moving on this now, sorry for the delay.

**Comment by brianhou** [comment]
Resolved by #357.
