### ISSUE TITLE
Customizable `frame_id` for `aikido_rviz` InteractiveMarkers

### ISSUE THREAD

**Issue by psigen** [personalrobotics/aikido#34]
Right now, `aikido_rviz` is hard-coded to publish in the `map` frame in two separate places.

https://github.com/personalrobotics/aikido/blob/master/aikido_rviz/src/FrameMarker.cpp#L62
https://github.com/personalrobotics/aikido/blob/master/aikido_rviz/src/BodyNodeMarker.cpp#L27

We should consolidate this to one location, and allow it to be changed to publish markers in another frame.  This would handle situations where something else in TF corresponds to the `kido` root frame.

**Comment by jslee02** [comment]
I believe this is resolved by #183.
