### ISSUE TITLE
Remove dtwarn redefinition

### ISSUE THREAD

**Issue by brianhou** [personalrobotics/aikido#348]
https://github.com/personalrobotics/aikido/pull/342#discussion_r170391883

There are a few times that `dtwarn` is redefined in `constraint::dart` because the namespace `dart` is ambiguous. We should remove them once they're no longer necessary.

**Comment by jslee02** [comment]
Upstream fix: https://github.com/dartsim/dart/pull/1010

**Comment by brianhou** [comment]
@jslee02 I think we should be able to update the DART version we depend on now, so we'll have that upstream fix. Can you try to address this? Thanks!

**Comment by jslee02** [comment]
I believe the redefinition warnings should be gone by now because AIKIDO is already using the DART version with the fix. The fix is in DART 6.4, and [AIKIDO depends on DART >= 6.6.2](https://github.com/personalrobotics/aikido/blob/ec943527925fbfdc4082aedf5f155883dcdcf095/CMakeLists.txt#L90).
