### ISSUE TITLE
Add StateSpace::equals()

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#383]
This is necessary to check the equality of two state spaces. One concrete use case would be testing if the space spaces of a planner and a problem are compatible.

**Comment by brianhou** [comment]
As @mkoval said in https://github.com/personalrobotics/aikido/pull/249#issuecomment-342697953, `State`s can only be used with the `StateSpace` instance that created them. We've been continuing to enforce this, so I don't think adding `StateSpace::equals` is a good idea; the planner and problem should share the same `StateSpace` instance in order for us to use them together.
