### ISSUE TITLE
Add `getBodyNodeOrThrow` to `aikido::robot::util`

### ISSUE THREAD

**Issue by gilwoolee** [personalrobotics/aikido#398]
`getBodyNodeOrThrow` seems to be useful enough to be defined in every robot classes, so let's have it in `robot::util`.

https://github.com/personalrobotics/libada/blob/master/src/Ada.cpp#L86

**Comment by jslee02** [comment]
It would be more general if it takes `MetaSkeleton` instead of `Skeleton`. Also, it should either (1) take const reference or (2) take `const ConstMetaSkeleton*` and check the nullity.

**Comment by Tonkel** [comment]
Pull Request #399

**Comment by brianhou** [comment]
Resolved by #399.
