### ISSUE TITLE
Use MetaSkeleton::getLockableReference() of DART

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#417]
Previously, AIKIDO had to use `Skeleton` rather than `MetaSkeleton` due to lack of mutex support in `MetaSkeleton`. In the latest release of DART (6.5.0), `MetaSkeleton` has this function so let's utilize it (see https://github.com/dartsim/dart/pull/1011).

**Comment by brianhou** [comment]
Merging with #447.
