### ISSUE TITLE
Expose ParabolicSmoother Parameters

### ISSUE THREAD

**Issue by Ponzel** [personalrobotics/aikido#441]
For the feeding demo, we want to be able to turn off shortcutting and set the `feasibilityCheckResolution` in `ParabolicSmoother`.

Suggested solution: Create something like `SmoothingParameters` and pass that to the `smoothPath` method which constructs the `ParabolicSmoother` with the correct parameters.

**Comment by brianhou** [comment]
Resolved by #579.
