### ISSUE TITLE
Mismatch in logmap representation of SE(2) states

### ISSUE THREAD

**Issue by aditya-vk** [personalrobotics/aikido#455]
AIKIDO assumes [\theta, x, y] while DART assumes [x, y, theta]. Everytime the the skeleton is set to a position the coordinates are set incorrectly.

One clean solution would be to have the state representation to be equivalent to that of DART, OMPL: 
[x, y, theta].

Is there any particular reason we chose this representation?

**Comment by jslee02** [comment]
The general convention in DART is that angular terms come first followed by linear term like `FreeJoint`. `PlanarJoint` (SE(2) joint) complied the rule when it's created, and then for some reason ["I" changed the order](https://github.com/dartsim/dart/commit/9b596e296a401fa347cfc037085409a4d61a1c1e#diff-440599fc9e290b829676f5e30c7a436b), which I don't remember the reason. :disappointed: 

I personally prefer angular term first, but this is just a matter of convention. So I'm open to follow DART's convention or OMPL's as long as we're consistent.

**Comment by aditya-vk** [comment]
We do not have to follow OMPL's convention since we never use their states anyway. It'd be better to stick to DART's convention IMO. I personally prefer angle at the end haha! Can we change it in DART then?
