### ISSUE TITLE
Increase minimum required ompl version greater than 0.13.0

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/aikido#471]
By #466, AIKIDO uses new API of ompl that are not available in OMPL 0.13. We need to increase the required minimum version of ompl accordingly.

I learned this looking at the build log of PPA: https://launchpadlibrarian.net/399640688/buildlog_ubuntu-trusty-amd64.aikido_0.3.0-378~201811300601~ubuntu14.04.1_BUILDING.txt.gz

**Comment by aditya-vk** [comment]
Addressed in #472
