### ISSUE TITLE
Issue warnings for skipped modules

### ISSUE THREAD

**Issue by egordon** [personalrobotics/aikido#488]
Currently, if there is a sub-module that fails to build (e.g. `planner_ompl` or `robot`), aikido will continue to build without alerting the user. Dependent repositories (e.g. `libada`) will then often fail to build. The user then has to re-build aikido with the `verbose` flag to see how to re-enable to un-built submodules.

Instead, would it be possible to ensure that the user is notified when a submodule isn't built (and the reason) to avoid that extra verbose build step?

**Comment by brianhou** [comment]
As we discussed in Slack, I think elevating `STATUS` messages to `WARNING`s would be reasonable.
