### ISSUE TITLE
Use Azure Pipelines for CI

### ISSUE THREAD

**Issue by brianhou** [personalrobotics/aikido#492]
Pros:
- Faster than Travis (10 parallel builds, rather than 5; VMs may also just be better)
- Longer build time limit (seems to be 6 hours, rather than 50 minutes)
- Default Ubuntu image is Xenial

Cons:
- We're currently using Travis

Before transitioning over, we should try setting up Azure Pipelines alongside Travis by making our scripts CI agnostic.

**Comment by egordon** [comment]
Addressed by #598
