### ISSUE TITLE
Compilation error: ambiguity w/ make_unique

### ISSUE THREAD

**Issue by egordon** [personalrobotics/aikido#530]
This issue has been fixed before in most files by #481 , but a recent update in GCC has brought it back to the fore.

Compilation errors with ambiguity in make_unique has been reproduced by myself, @jt10y , and Haoran.

I'll make a quick branch to fix it.

**Comment by jslee02** [comment]
I hope #527 is first merged so that this kind of erros can be captured by the CI tests.

**Comment by jslee02** [comment]
Addressed by #527
