### ISSUE TITLE
Expose custom velocityLimits in ConcreteRobot retimers

### ISSUE THREAD

**Issue by egordon** [personalrobotics/aikido#558]
Currently, all retiming functions just pull the velocity limits directly from the MetaSkeleton. To get around this, ADA currently sets the MetaSkeleton velocity limits manually, calls the retimer, and then resets them to the previous values.

Instead, this should be exposed as an optional argument (default is to use the MetaSkeleton), as there are times where we may want the robot to move more slowly for a specific trajectory.

See comments on `libada` PR40 for more details (https://github.com/personalrobotics/libada/pull/40).

**Comment by brianhou** [comment]
I wonder if this makes sense to add as another possible field in the parameter struct for post-processors, which @sniyaz started working on in https://github.com/personalrobotics/libherb/pull/114. (Those struct definitions should eventually move to aikido.)

**Comment by sniyaz** [comment]
Closed now that https://github.com/personalrobotics/aikido/pull/579 is merged.
