### ISSUE TITLE
ConcreteManipulator should be inheriting from ConcreteRobot?

### ISSUE THREAD

**Issue by gilwoolee** [personalrobotics/aikido#563]
Currently, 

- `Manipulator` inherits `Robot`
- `ConcreteRobot` inherits `Robot`
- `ConcreteManipulator` inherits `Manipulator`

the only difference between `Manipulator` and `Robot` is that `Manipulator` has `getHand` class. 
I think above inheritance makes sense conceptually, but code-wise, there's a lot of code duplicates between `ConcreteManipulator` and `ConcreteRobot`, esp. regarding TSR related methods.

I think we need to add `ConcreteRobot` to `ConcreteManipulator`'s parent class list, i.e. 
- `ConcreteManipulator` inherits `Manipulator` and `ConcretRobot`

**Comment by gilwoolee** [comment]
@brianhou @aditya-vk @sniyaz @egordon  Any thoughts?

**Comment by egordon** [comment]
Resolved by the Robot API overhaul (#593 )
