### ISSUE TITLE
Travis build is broken with catkin_tools >= 0.4

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/aikido#58]

**Comment by mkoval** [comment]
I was mistaken. This appears to be a transient issue that was masked by the fact that `catkin_tools` >= 0.4 is hiding all command line output on Travis. We likely need to modify the flags we pass to the `build` verb to avoid piping `stdout` and `stderr` to log files.

**Comment by brianhou** [comment]
Not sure what the original problem was, but closing I think our Travis builds are currently correct (aside from the fact that the Xenial & Bionic builds don't pass).
