### ISSUE TITLE
Use custom predicate for comparing Eigen matrices

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/aikido#63]
I wrote a custom GTest predicate `CompareEigenMatrices` for comparing `Eigen` matrices. We should replace all of our `EXPECT_TRUE(a.isApprox(b))` calls with this predicate. There are a few advantages:
1. reduces code duplication
2. generates **much** more informative error messages
3. handles comparing against a matrix that contains zero elements.

**Comment by brianhou** [comment]
I think this now exists in https://github.com/personalrobotics/aikido/blob/master/tests/eigen_tests.hpp as of #32.
