### ISSUE TITLE
Excluded external dependencies from coveralls

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/aikido#81]
Our test coverage is currently being distorted by the presence of Hauser parabolic smoother. We don't use all of the functionality of the external library in our wrapper, so we clearly will not test all of it.

We should disable coveralls on these source files to get a more accurate reflection of our actual test coverage.

**Comment by psigen** [comment]
Fixed by 6e90ed0ac241dc0031e766d0f3203001869a1f4e?

**Comment by jslee02** [comment]
I also believe this is resolved by #32. Please reopen if it's not true.
