### ISSUE TITLE
KinematicSimulationTrajectoryExecutor assumes trajectory's getStartTime is zero.

### ISSUE THREAD

**Issue by gilwoolee** [personalrobotics/aikido#99]
Current implementation of `KinematicSimulationTrajectoryExecutor::spin()` assumes that the trajectory starts at `t=0`. We should extend this to handle when the startTime is not zero.

**Comment by Shushman** [comment]
I believe this is handled in https://github.com/personalrobotics/aikido/blob/master/src/control/KinematicSimulationTrajectoryExecutor.cpp#L81

@gilwoolee can you confirm? Then I'll close.

**Comment by gilwoolee** [comment]
Yes. we can close it.
